repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
        exclude: "tests/((commands|data|providers/test_uv_provider)/|test_).+"
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '\.svg$'
      - id: debug-statements
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"] # for mkdocs.yml
      - id: detect-private-key

  - repo: local
    hooks:
      - id: check-test-files
        name: Check test files exist
        entry: powershell -NonInteractive -NoProfile -Command "& {./scripts/check-test-files.ps1 *>&1 | Select-Object -Last 1; exit $LASTEXITCODE}"
        language: system
        pass_filenames: false
        types: [file]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: Run codespell to check for common misspellings in files
        language: python
        types: [text]
        args: ["--write-changes"]
        additional_dependencies:
          - tomli

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit

  - repo: https://github.com/mcgrue/pre-commit-hook-MAKE-SOME-NOISE #needs to be the last one in the list
    rev: 71ef4ac
    hooks:
      - id: make-some-noise
        # language: python
        args: [
          --url-alive,
          "http://SWORDFISH:22222",
          --url-fail,
          "http://swordfish:22222/SDL_assert",
          --url-pass,
          "http://SWORDFISH:22222/DOCTEST_ALL_TESTS_PASS",
          --url-error,
          "http://swordfish:22222/SDL_assert",
        ]
        # additional_dependencies: [requests, argparse]
