export const BACKEND_PORT_FILE = `.port_backend`;
export const GIT_VERSION = `GIT_VERSION_REPLACED_BY_CI_DO_NOT_CHANGE`;
export const DEPLOY_TIMESTAMP = `DEPLOY_TIMESTAMP_REPLACED_BY_CI_DO_NOT_CHANGE`;
