name: Deploy
on:
  push:
    branches: breaditor
  pull_request:
    branches: breaditor

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Create port files
        run: |
          echo "8025" > .port_backend
          echo "5000" > .port_frontend

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"
      
      - name: Test step
        run: "yarn test"

      - name: Fail if there are any .ts or .tsx files in the project without a .test.ts or .test.tsx file
        shell: pwsh
        run: ./scripts/check-test-files.ps1
      
      - name: Fail if required shiboleths for replacement are missing
        shell: pwsh
        run: |
          # fail if GIT_VERSION_REPLACED_BY_CI_DO_NOT_CHANGE or DEPLOY_TIMESTAMP_REPLACED_BY_CI_DO_NOT_CHANGE are missing from backend/constants.ts
          $content = Get-Content "backend/constants.ts" -Raw
          if (-not ($content -match "GIT_VERSION_REPLACED_BY_CI_DO_NOT_CHANGE" -and $content -match "DEPLOY_TIMESTAMP_REPLACED_BY_CI_DO_NOT_CHANGE")) {
              Write-Error "Required replacement tokens are missing from backend/constants.ts"
              exit 1
          }

      - name: Replace ci variables 
        shell: pwsh
        run: |
          # replace GIT_VERSION_REPLACED_BY_CI_DO_NOT_CHANGE in backend/constants.ts with the 7-digit git sha
          $content = Get-Content "backend/constants.ts" -Raw
          $gitSha = "${{ github.sha }}".Substring(0,7)
          $newContent = $content -replace "GIT_VERSION_REPLACED_BY_CI_DO_NOT_CHANGE", $gitSha
          Set-Content "backend/constants.ts" $newContent
          
          # replace DEPLOY_TIMESTAMP_REPLACED_BY_CI_DO_NOT_CHANGE in backend/constants.ts with the ISO timestamp for now
          $timestamp = [DateTime]::UtcNow.ToString("o")
          $newContent = $newContent -replace "DEPLOY_TIMESTAMP_REPLACED_BY_CI_DO_NOT_CHANGE", $timestamp
          Set-Content "backend/constants.ts" $newContent

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: "ignore"

      - name: Transfer build artifacts
        run: |
          echo "cleaning up stage"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "rm -rf ~/spritewright || true"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "mkdir ~/spritewright || true"
         
          echo "uploading to stage"
          scp -r dist/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/spritewright/front
          rsync -av --exclude-from='.gitignore' ./* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:~/spritewright/back

          echo "stopping service"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "sudo systemctl stop spritewright.service"

          echo "deleting production"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "rm -rf ${{ secrets.FRONTEND_DEPLOY_PATH }}/*"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "rm -rf ${{ secrets.BACKEND_DEPLOY_PATH }}/*"

          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "mkdir ${{ secrets.FRONTEND_DEPLOY_PATH }} || true"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "mkdir ${{ secrets.BACKEND_DEPLOY_PATH }} || true"

          echo "copying to production"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cp -r ~/spritewright/front/* ${{ secrets.FRONTEND_DEPLOY_PATH }}"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cp -r ~/spritewright/back/* ${{ secrets.BACKEND_DEPLOY_PATH }}"

          echo "starting service"
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "sudo systemctl start spritewright.service"

